// Generated by https://quicktype.io

export interface User {
    id:           number;
    email:        string;
    password:     string;
    fullName:     string;
    joinedOn:     string;
    incomes:      null;
    expenditures: null;
}
