// Generated by https://quicktype.io

import { Expenditure } from "./Expenditure";
import { Income } from "./Income";

export interface UserDetailResponse {
    userId:       number;
    fullName:     string;
    incomes:      Income[];
    expenditures: Expenditure[];
}


